# Using windows image with python in it
FROM winamd64/python:3.9-windowsservercore-1809

# Changing the working directory
WORKDIR /app


ENV APP=pkn.py

# Coping whole contence to the app folder
COPY . .

# Running the powershell for futher commands
RUN powershell -Command Add-WindowsFeature Web-Server

# Installing requiremets for the project
RUN pip install -r requirements.txt

# Run the tests
RUN python test.py
